name: publish
on:
    push:
        branches:
            - main
jobs:
    build-docker-image:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            -   name: Get Version
                run: VERSION=$(cat VERSION)
            -   name: Build the angular app
                run: |
                    docker run --rm -v ./:/app trion/ng-cli ng build
            -   name: Build the Docker image
                run: |
                    VERSION=$(cat VERSION)
                    docker build --tag ghcr.io/einspunktnull/schmierschiss:$VERSION --tag ghcr.io/einspunktnull/schmierschiss:latest .
            -   name: Login at GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Push The Docker image to the GitHub Container Registry
                run: |
                    ./build_docker_image.sh
                    VERSION=$(cat VERSION)
                    docker push ghcr.io/einspunktnull/schmierschiss --all-tags
