name: publish
on:
  push:
    branches:
      - main
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        #        run: ./build.sh
        run: |
          docker build . --tag ghcr.io/einspunktnull/schmierschiss:latest
      - name: Push to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        run: docker push ghcr.io/einspunktnull/schmierschiss:latest
