name: publish
on:
    push:
        branches:
            - main
jobs:
    build-docker-image:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            -   name: Use Node
                uses: actions/setup-node@v1
                with:
                    node-version: '16.x'
            -   name: Install Node deps
                run: npm ci
            -   name: Install dependencies
                run: npm ci
            -   name: Build the angular app
                run: npm run build:ci
#            -   name: Test
#                run: npm run test:ci
            -   name: Build the Docker image
                run: |
                    VERSION=$(scripts/read_version_from_package_json.sh .)
                    docker build --tag ghcr.io/einspunktnull/schmierschiss:$VERSION --tag ghcr.io/einspunktnull/schmierschiss:latest .
            -   name: Login at GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Push The Docker image to the GitHub Container Registry
                run: |
                    ./build_docker_image.sh
                    VERSION=$(scripts/read_version_from_package_json.sh .)
                    docker push ghcr.io/einspunktnull/schmierschiss --all-tags
